-- MySQL Script generated by MySQL Workbench
-- Thu Aug 19 11:40:17 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exercicio1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercicio1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercicio1` DEFAULT CHARACTER SET utf8 ;
USE `exercicio1` ;

-- -----------------------------------------------------
-- Table `exercicio1`.`aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`aluno` (
  `idaluno` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `matricula` VARCHAR(10) NOT NULL,
  `cpf` INT NOT NULL,
  `telefone` VARCHAR(15) NULL,
  PRIMARY KEY (`idaluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1`.`disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`disciplina` (
  `iddisciplina` INT NOT NULL,
  `sigla` VARCHAR(5) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `curso` VARCHAR(45) NOT NULL,
  `media` DOUBLE NOT NULL,
  PRIMARY KEY (`iddisciplina`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio1`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio1`.`matricula` (
  `idmatricula` INT NOT NULL,
  `nota` DOUBLE NOT NULL,
  `data` DATE NOT NULL,
  `aluno_idaluno` INT NOT NULL,
  `disciplina_iddisciplina` INT NOT NULL,
  PRIMARY KEY (`idmatricula`),
  INDEX `fk_matricula_aluno_idx` (`aluno_idaluno` ASC) VISIBLE,
  INDEX `fk_matricula_disciplina1_idx` (`disciplina_iddisciplina` ASC) VISIBLE,
  CONSTRAINT `fk_matricula_aluno`
    FOREIGN KEY (`aluno_idaluno`)
    REFERENCES `exercicio1`.`aluno` (`idaluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_matricula_disciplina1`
    FOREIGN KEY (`disciplina_iddisciplina`)
    REFERENCES `exercicio1`.`disciplina` (`iddisciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO aluno (idaluno, nome, matricula, cpf, telefone) VALUES
(1, 'Thiago', 'PE300712X', 123123123, '(18)123123'),
(2, 'Fulemo', 'PE1234456', 222333444, '(11)122234');

INSERT INTO disciplina (iddisciplina, sigla, nome, curso, media) VALUES
(1, 'BD2', 'Banco de Dados 2', 'BCC', 10),
(2, 'ED2', 'Estrutura de Dados 2', 'BCC', 9);

INSERT INTO matricula (idmatricula, nota, data, aluno_idaluno, disciplina_iddisciplina) VALUES
(1, 10, '2021/01/01', 1, 1),
(2, 9, '2021/01/01', 2, 2);

SELECT A.idaluno, A.nome, A.matricula FROM aluno A, matricula M WHERE M.disciplina_iddisciplina = 1 and M.aluno_idaluno = idaluno;
SELECT A.idaluno, A.nome, A.matricula FROM aluno A, matricula M, disciplina D WHERE D.iddisciplina = 1 and M.disciplina_iddisciplina = iddisciplina and D.media > 9;
SELECT A.idaluno, A.nome, A.matricula FROM aluno A, matricula M, disciplina D WHERE D.iddisciplina = 1 and M.disciplina_iddisciplina = iddisciplina and D.curso = 'BCC';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;