-- MySQL Script generated by MySQL Workbench
-- Thu Aug 19 16:02:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema exercicio2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema exercicio2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `exercicio2` DEFAULT CHARACTER SET utf8 ;
USE `exercicio2` ;

-- -----------------------------------------------------
-- Table `exercicio2`.`filme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio2`.`filme` (
  `idfilme` INT NOT NULL,
  `titulo` VARCHAR(45) NOT NULL,
  `genero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idfilme`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio2`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio2`.`cliente` (
  `idcliente` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `endereco` VARCHAR(80) NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `exercicio2`.`emprestimo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `exercicio2`.`emprestimo` (
  `idemprestimo` INT NOT NULL,
  `dataemp` DATE NOT NULL,
  `valor` DOUBLE NOT NULL,
  `pago` VARCHAR(15) NULL,
  `cliente_idcliente` INT NOT NULL,
  `filme_idfilme` INT NOT NULL,
  PRIMARY KEY (`idemprestimo`),
  INDEX `fk_emprestimo_cliente_idx` (`cliente_idcliente` ASC) VISIBLE,
  INDEX `fk_emprestimo_filme1_idx` (`filme_idfilme` ASC) VISIBLE,
  CONSTRAINT `fk_emprestimo_cliente`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `exercicio2`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emprestimo_filme1`
    FOREIGN KEY (`filme_idfilme`)
    REFERENCES `exercicio2`.`filme` (`idfilme`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

INSERT INTO filme (idfilme, titulo, genero) VALUES
(1, 'Evangelion: 2.0 You Can (Not) Advance', 'Anime'),
(2, 'Evangelion: 3.0+1.0 Thrice Upon a Time', 'Ficcao Cientifica');

INSERT INTO cliente (idcliente, nome, telefone, endereco) VALUES
(1, 'Thiago', '(18)123123', 'Rua Pascoal Alexandre'),
(2, 'Fulamo', '(21)321321', 'Rua Oosma Kako');

INSERT INTO emprestimo (idemprestimo, dataemp, valor, pago, cliente_idcliente, filme_idfilme) VALUES
(1, '2021/08/10', 30, 'Sim', 1, 1),
(2, '2021/08/13', 50, 'Nao', 2, 2);

SELECT F.idfilme, F.titulo, F.genero FROM filme F WHERE F.genero = 'Ficcao Cientifica';
SELECT F.idfilme, F.titulo, F.genero FROM  filme F, cliente C, emprestimo E WHERE C.idcliente = 1 and E.cliente_idcliente = idcliente and E.filme_idfilme = F.idfilme;
SELECT E.idemprestimo, E.dataemp, E.valor, E.cliente_idcliente FROM cliente C, emprestimo E WHERE C.idcliente = 1 and E.cliente_idcliente = idcliente;
SELECT E.dataemp, E.valor FROM emprestimo E WHERE E.dataemp = '2021/08/10';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
